apiVersion: 1

datasources:
  - name: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    isDefault: true
    editable: true
    jsonData:
      httpMethod: GET
      serviceMap:
        datasourceUid: tempo
    uid: tempo
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    editable: true
    uid: prometheus
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    editable: true
    uid: loki
    jsonData:
      derivedFields:
        - datasourceUid: tempo
          matcherRegex: "trace_id=(\\w+)"
          name: TraceID
          url: "$${__value.raw}"
